import smtplib
from email.message import EmailMessage
import os
from pathlib import Path
from dotenv import load_dotenv

# Load backend/.env
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(_PROJECT_ROOT / "backend" / ".env")
load_dotenv(_PROJECT_ROOT / "backend" / "env") # fallback just in case depending on how you named it

def send_employer_notification(employer_email: str, job_title: str, user_id: str, resume_filename: str, resume_content: str):
    smtp_server = os.getenv("SMTP_SERVER", "")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USERNAME", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    smtp_sender = os.getenv("SMTP_SENDER", smtp_user)

    if not smtp_server or not smtp_user or not smtp_pass:
        print("DEBUG: [email_service] SMTP credentials not configured. Skipping email notification.")
        return False

    msg = EmailMessage()
    msg['Subject'] = f"New Application: {job_title}"
    msg['From'] = smtp_sender
    msg['To'] = employer_email

    html_content = f"""
    <html>
        <body>
            <h2>New Job Application Received</h2>
            <p><strong>Job Title:</strong> {job_title}</p>
            <p><strong>Candidate Details:</strong> You have a new candidate (User ID: {user_id}) applying for this position.</p>
            <p><strong>Resume File Name:</strong> {resume_filename}</p>
            <hr />
            <h3>Candidate Resume Details</h3>
            <pre style="white-space: pre-wrap; font-family: sans-serif; background-color: #f9f9f9; padding: 10px; border-radius: 5px;">{resume_content}</pre>
            <hr />
            <p><small>This email was automatically generated by the AIResume Application.</small></p>
        </body>
    </html>
    """
    
    msg.set_content(f"New application received for {job_title}. Please view this email in an HTML compatible client.")
    msg.add_alternative(html_content, subtype='html')

    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        print(f"DEBUG: [email_service] Successfully sent application email to {employer_email}")
        return True
    except Exception as e:
        print(f"DEBUG: [email_service] Failed to send email to {employer_email}: {e}")
        return False
